Application/Models/Admin/AddBusRouteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Application.Models.Admin
{
    public class AddBusRouteViewModel
    {
        [Required]
        public string Bus { get; set; }

        public IEnumerable<string> First { get; set; }

        public IEnumerable<string> Second { get; set; }
            
        public IEnumerable<SelectListItem> Stops { get; set; }

        public IEnumerable<SelectListItem> Buses { get; set; }
    }
}

Application/Models/Admin/AddBusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Globalization;
using System.ComponentModel.DataAnnotations;

namespace Application.Models.Admin
{
    public class AddBusViewModel
    {
        [Required]
        [MaxLength(4)]
        [RegularExpression(@"(\d+)[А-Я]",ErrorMessage ="Неправильный номер")]      
        public string Number { get; set; }
    }
}

Application/Models/Admin/AddSheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Application.Models.Admin
{
    public class AddSheduleViewModel
    {
        [Required]
        public string Bus { get; set; }

        [Required]
        public string Stop { get; set; }
        
        [Required]
        public string EndStop { get; set; }

        public IEnumerable<string> Days { get; set; }

        [Required]
        public IEnumerable<string> SelectedDays { get; set; }

        public IEnumerable<SelectListItem> Buses { get; set; }

        [Required]
        public IEnumerable<TimeSpan> Shedule { get; set; }
    }
}

Application/Models/Admin/AddStopViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Application.Models.Admin
{
    public class AddStopViewModel
    {
        [Required]
        [MaxLength(40)]
        public string Name { get; set; }
    }
}

Application/Models/Admin/DeleteBusRouteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Application.Models.Admin
{
    public class DeleteBusRouteViewModel
    {
        [Required]
        public string Bus { get; set; }

        public IEnumerable<SelectListItem> Buses { get; set; }
    }
}

Application/Models/Admin/DeleteBusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Application.Models.Admin
{
    public class DeleteBusViewModel
    {
        [Required]
        public string Bus { get; set; }
        public List<SelectListItem> Buses { get; set; }
    }
}

Application/Models/Admin/DeleteSheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Models.Admin
{
    public class DeleteSheduleViewModel
    {
        public IEnumerable<string> Buses { get; set; }

        [Required]
        public string Bus { get; set; }
        [Required]
        public string Stop { get; set; }
        [Required]
        public string EndStop { get; set; }
        [Required]
        public string Days { get; set; }
    }
}

Application/Models/Admin/DeleteStopViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Application.Models.Admin
{
    public class DeleteStopViewModel
    {
        [Required]
        public string Stop { get; set; }
        public List<SelectListItem> Stops { get; set; }
    }
}

Application/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Application.Models.Admin;
using System.Text;
using System.Text.RegularExpressions;
using Application.Models;
using System.Reflection;
using Domain.Models;
using Domain.SheduleParsers.Abstract;
using Application.Infrastructure.SheduleParserFactory.Abstract;

namespace Application.Controllers
{
    [Authorize(Roles = "admin")]
    //[OutputCache(Duration = 3600, SqlDependency = "shedule:Shedules")]
    public class AdminController : Controller
    {
        private ISheduleParserFactory factory;
        private IRepository<Bus> busRepository;
        private IRepository<Stop> stopsRepository;
        private IRepository<TimeTable> timeTablesRepository;
        private IRepository<Shedule> shedulesRepository;
        private IRepository<City> citiesRepository;

        public AdminController(IRepository<Bus> _busRepository,
                               IRepository<Stop> _stopsRepository,
                               IRepository<TimeTable> _timeTablesRepository,
                               IRepository<Shedule> _shedulesRepository,
                               IRepository<City> _citiesRepository,
                               ISheduleParserFactory _factory)
        {
            busRepository = _busRepository;
            stopsRepository = _stopsRepository;
            timeTablesRepository = _timeTablesRepository;
            shedulesRepository = _shedulesRepository;
            citiesRepository = _citiesRepository;
            factory = _factory;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddFromFile()
        {
            AddFileViewModel model = new AddFileViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddFromFile(AddFileViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int cityId = (int)Session["City"];
                    var city = citiesRepository.GetByID(cityId);
                    var fileName = this.HttpContext.Request.MapPath("~/Content/shedule" + cityId + ".xls");
                    model.file.SaveAs(fileName);

                    ISheduleParser parser = factory.Create(city.Name.ToLower());
                    var shedule = parser.Parse(fileName, city);

                    timeTablesRepository.InsertRange(shedule);
                    TempData["Success"] = "Расписание добавлено";
                }
                catch(Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    TempData["Erors"] = "Ошибка при обработке файла, проверьте правильность файла";
                }
                return RedirectToAction("AddFromFile");
            }
            return View(model);
        }




        [HttpGet]
        public ActionResult AddBus()
        {
            AddBusViewModel model = new AddBusViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddBus(AddBusViewModel model)
        {
            int cityId = (int)Session["City"];
            if(ModelState.IsValid)
            {
                try
                {
                    busRepository.Insert(new Bus { Number = model.Number, CityId = cityId });
                    TempData["Success"] = "Запись добавлена";
                    model = new AddBusViewModel();
                }
                catch(Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    ModelState.AddModelError("", "Ошибка при добавлении записи. Повторите попытку позже");
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteBus()
        {
            int cityId = (int)Session["City"];

            DeleteBusViewModel model = new DeleteBusViewModel
            {
                Buses = new List<SelectListItem>(busRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem {Value = x.Id.ToString(), Text = x.Number }))
            };
            return View(model);
        }

        [HttpDelete]
        public ActionResult DeleteBus(DeleteBusViewModel model)
        {
            int cityId = (int)Session["City"];
            if (ModelState.IsValid)
            { 
                try
                {
                    busRepository.Delete(int.Parse(model.Bus));
                    model.Bus = "";
                    TempData["Success"] = "Запись удалена";
                }
                catch(Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    ModelState.AddModelError("", "Ошибка при удалении записи. Повторите попытку позже");
                }
            }
            model.Buses = new List<SelectListItem>(busRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Number }));
            return View(model);
        }

        [HttpGet]
        public ActionResult AddStop()
        {
            AddStopViewModel model = new AddStopViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddStop(AddStopViewModel model)
        {
            int cityId = (int)Session["City"];
            if(stopsRepository.Get(x => x.CityId == cityId && x.Name.ToLower() == model.Name.ToLower()).Any())
            {
                ModelState.AddModelError("","Остановка с таким названием уже существует");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    stopsRepository.Insert(new Stop { CityId = cityId, Name = model.Name });
                    TempData["Success"] = "Запись добавлена";
                    model = new AddStopViewModel();
                }
                catch (Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    ModelState.AddModelError("", "Ошибка при добавлении записи. Повторите попытку позже");
                }
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteStop()
        {
            int cityId = (int)Session["City"];

            DeleteStopViewModel model = new DeleteStopViewModel
            {
                Stops = new List<SelectListItem>(stopsRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }))
            };
            return View(model);
        }

        [HttpDelete]
        public ActionResult DeleteStop(DeleteStopViewModel model)
        {
            int cityId = (int)Session["City"];
            if (ModelState.IsValid)
            {
                try
                {
                    stopsRepository.Delete(int.Parse(model.Stop));
                    model.Stop = "";
                    TempData["Success"] = "Запись удалена";
                }
                catch (Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    ModelState.AddModelError("", "Ошибка при удалении записи. Повторите попытку позже");
                }
            }
            model.Stops = new List<SelectListItem>(stopsRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name }));
            return View(model);
        }

        [HttpGet]
        public ActionResult AddBusRoute()
        {
            int cityId = (int)Session["City"];
            var buses = busRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Number });
            var stops = stopsRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name });
            AddBusRouteViewModel model = new AddBusRouteViewModel { Buses = buses, Stops = stops  };
            return View(model);
        }


        [HttpPost]
        public ActionResult AddBusRoute(AddBusRouteViewModel model)
        {
            int cityId = (int)Session["City"];
            IEnumerable<TimeTable> first = CreateTimeTableRange(model.First, model.Bus);
            IEnumerable<TimeTable> second = CreateTimeTableRange(model.Second, model.Bus);
            if (ModelState.IsValid)
            {
                try
                {
                    timeTablesRepository.InsertRange(first);
                    timeTablesRepository.InsertRange(second);
                    model.Bus = null;
                    model.First = null;
                    model.Second = null;
                    TempData["Success"] = "Запись добавлена";
                }
                catch(Exception ex)
                {
                    NLog.LogManager.GetCurrentClassLogger().Error(ex);
                    ModelState.AddModelError("", "Ошибка при добавлении записи. Повторите попытку позже");
                }
            }
            var buses = busRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Number });
            var stops = stopsRepository.Get(x => x.CityId == cityId).Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name });
            model.Buses = buses;
            model.Stops = stops;
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteBusRoute()
        {
            int cityId = (int)Session["City"];
            var buses = timeTablesRepository.Get(x => x.Bus.CityId == cityId)
                                            .Select(x => x.Bus)
                                            .Distinct()

Application/Controllers/AdminManageController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Application.Models.AdminManage;

namespace Application.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminManageController : Controller
    {
        private const int usersOnPage = 10;
        private ApplicationUserManager _userManager;
        public AdminManageController()
        {
        }

        public AdminManageController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [HttpGet]
        public ActionResult Users(string searchValue="All",int page = 1)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Items", GetItems(page,searchValue));
            }
            return View(GetItems(page, searchValue));
        }

        [HttpGet]
        [ActionName("User")]
        public async Task<ActionResult> UserInfo(string id)
        {
            var roles = await UserManager.GetRolesAsync(id);           
            var user = await UserManager.FindByIdAsync(id);

            UserViewModel model = new UserViewModel()
            {
                Name = user.UserName,
                Email = user.Email ?? "-",
                Roles = roles,
                Id = id
            };
            return View(model);
        }
  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> SetOnRole(string Id, string role = "admin")
        {
            if(Id != null && role != null)
            { 
            var result = await UserManager.AddToRoleAsync(Id, role);
            }

            return RedirectToAction("User",new {id = Id });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveFromRole(string Id, string role = "admin")
        {
            if (Id != null && role != null)
            {
                var result = await UserManager.RemoveFromRoleAsync(Id, role);
            }

            return RedirectToAction("User", new { id = Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string Id)
        {
            if (Id != null)
            {
                var user = await UserManager.FindByIdAsync(Id);
                var result = await UserManager.DeleteAsync(user);
            }

            return RedirectToAction("Users");
        }


        private IEnumerable<Application.Models.ApplicationUser> GetItems(int page, string searchValue)
        {
            Func<Models.ApplicationUser, bool> term;
            if (searchValue == "All" || searchValue == null)
            {
                term = x => x.UserName != User.Identity.Name;
            }
            else
            {
                term = x => x.UserName.Contains(searchValue) && x.UserName != User.Identity.Name;
            }
            return UserManager.Users.Where(term)
                                    .OrderBy(x => x.UserName)
                                    .Skip((page * usersOnPage) - usersOnPage)
                                    .Take(usersOnPage);
        }



    }
}

Application/Views/Admin/Add.cshtml
@model Application.Models.Admin.AddFileViewModel
@{
    ViewBag.Title = "Add";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@TempData["Erors"]</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Создать расписание</h3>
    </div>
    @Html.ValidationSummary()

    <div class="list-group">
        <div class="list-group-item">
            @using (Html.BeginForm("Add", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <h4 class="text-muted">Выберите файл</h4>
                    @Html.ValidationMessageFor(x => x.file)
                    @Html.TextBoxFor(x => x.file, null, new { type = "file", accept = "application/vnd.ms-excel" })

                    <hr />
                    <input type="submit" value="Загрузить" class="btn btn-default" />
                </div>
            }
        </div>
    </div>


</blockquote>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        jQuery.validator.unobtrusive.adapters.add(
    'filesize', ['maxsize'], function (options) {
        options.rules['filesize'] = options.params;
        if (options.message) {
            options.messages['filesize'] = options.message;
        }
    }
    );

        jQuery.validator.addMethod('filesize', function (value, element, params) {
            if (element.files.length < 1) {
                // No files selected
                return true;
            }

            if (!element.files || !element.files[0].size) {
                // This browser doesn't support the HTML5 API
                return true;
            }
            var total = 0;
            for (var i = 0; i < element.files.length; i++)
                total += element.files[i].size;
            return total < params.maxsize;
        }, '');
    </script>
}

Application/Views/Admin/AddBus.cshtml
@model Application.Models.Admin.AddBusViewModel

@{
    ViewBag.Title = "Добавить автобус";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Добавить автобус</h3>
    </div>
    @using (Html.BeginForm("AddBus", "Admin", FormMethod.Post))
    {
        <div class="input-group">
            @Html.TextBoxFor(x => x.Number, new { @class = "form-control" })
            <button type="submit" class="btn btn-success input-group-addon">Добавить</button>
        </div>
    }
</blockquote>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/AddBusRoute.cshtml
@model Application.Models.Admin.AddBusRouteViewModel

@{
    ViewBag.Title = "Добавить маршрут";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Добавить маршрут</h3>
    </div>
    @using (Html.BeginForm("AddBusRoute", "Admin", FormMethod.Post))
    {
        <div class="input-group">
            <span class="input-group-addon">Выберите автобус</span>
            @Html.DropDownListFor(x => x.Bus, Model.Buses, new { @class = "form-control" })
        </div>

        <hr/>
        <div class="panel panel-default">
            <div class="panel-heading">Первый маршрут</div>
            <div class="panel-body">
                <ul class="list-group" id="FirstRouteTable">
                    @if(Model.First != null)
                    {
                        foreach (var stop in Model.First)
                        {
                            <li class="list-group-item"><input type="hidden" name="first" value= @stop >@Model.Stops.Where(x => x.Value == stop).First().Text</li>
                        }
                    }
                </ul>
                <div class="input-group">
                    @Html.DropDownList("SelectedStop", Model.Stops, new {id = "SelectedStop", @class = "form-control" })
                    <button class="btn btn-success input-group-addon" onclick="AddStopToRoute(event,'SelectedStop','FirstRouteTable','first')">Добавить</button>
                </div>
            </div>
        </div>
        <hr />
        <div class="panel panel-default">
            <div class="panel-heading">Второй маршрут</div>
            <div class="panel-body">
                <ul class="list-group" id="SecondRouteTable">
                    @if (Model.Second != null)
                    {
                        foreach (var stop in Model.Second)
                        {
                            <li class="list-group-item"><input type="hidden" name="second" value = @stop>@Model.Stops.Where(x => x.Value == stop).First().Text</li>
                        }
                    }
                </ul>
                <div class="input-group">
                    @Html.DropDownList("Stop", Model.Stops, new { id = "Stop", @class = "form-control" })
                    <button class="btn btn-success input-group-addon" onclick="AddStopToRoute(event,'Stop','SecondRouteTable','second')">Добавить</button>
                </div>
            </div>
        </div>
        <hr />
        <button type="submit" class="btn btn-primary">Сохранить</button>
    }
</blockquote>

@section scripts
{
    @Scripts.Render("~/Scripts/Admin/AddBusRoute.js")
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/AddFromFile.cshtml
@model Application.Models.Admin.AddFileViewModel
@{
    ViewBag.Title = "Add";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@TempData["Erors"]</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Создать расписание</h3>
    </div>
    @Html.ValidationSummary()

    <div class="list-group">
        <div class="list-group-item">
            @using (Html.BeginForm("AddFromFile", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <h4 class="text-muted">Выберите файл</h4>
                    @Html.ValidationMessageFor(x => x.file)
                    @Html.TextBoxFor(x => x.file, null, new { type = "file", accept = "application/vnd.ms-excel" })

                    <hr />
                    <input type="submit" value="Загрузить" class="btn btn-default" />
                </div>
            }
        </div>
    </div>


</blockquote>


@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        jQuery.validator.unobtrusive.adapters.add(
    'filesize', ['maxsize'], function (options) {
        options.rules['filesize'] = options.params;
        if (options.message) {
            options.messages['filesize'] = options.message;
        }
    }
    );

        jQuery.validator.addMethod('filesize', function (value, element, params) {
            if (element.files.length < 1) {
                // No files selected
                return true;
            }

            if (!element.files || !element.files[0].size) {
                // This browser doesn't support the HTML5 API
                return true;
            }
            var total = 0;
            for (var i = 0; i < element.files.length; i++)
                total += element.files[i].size;
            return total < params.maxsize;
        }, '');
    </script>
}

Application/Views/Admin/AddShedule.cshtml
@model Application.Models.Admin.AddSheduleViewModel

@{
    ViewBag.Title = "Добавить расписание";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote class="blockquote">
@using (Html.BeginForm("AddShedule", "Admin", FormMethod.Post))
{
    <div class="row">

        <div class="col-sm-3">
            <h4 class="text-muted">Номер</h4>
            @Html.DropDownListFor(x => x.Bus, Model.Buses, "", new { @class = "form-control", onchange = "SelectNumber();" })
        </div>
        <div class="col-sm-3">
            <h4 class="text-muted">Остановка</h4>
            @Html.DropDownListFor(x => x.Stop, new SelectList(new List<string>()), "", new { @class = "form-control", onchange = " SelectStop();" })
        </div>
        <div class="col-sm-3">
            <h4 class="text-muted">Направление</h4>
            @Html.DropDownListFor(x => x.EndStop, new SelectList(new List<string>()), "", new { @class = "form-control" })
        </div>
        <div class="col-sm-3">
            <h4 class="text-muted">Дни</h4>
            @Html.ListBox("SelectedDays", new MultiSelectList(Model.Days), new { size = 10 })
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-sm-12">
            @Html.TextAreaFor(x => x.Shedule, new { @class = "form-control", rows = 10 })
        </div>
    </div>

    <hr/>
    <button type="submit" class="btn btn-success">Добавить</button>
}
</blockquote>

@section scripts
{
    @Scripts.Render("~/Scripts/Admin/AddShedule.js")
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/DeleteBus.cshtml
@model Application.Models.Admin.DeleteBusViewModel
@{
    ViewBag.Title = "Удалить автобус";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Удалить автобус</h3>
    </div>
    @using (Html.BeginForm("DeleteBus", "Admin", FormMethod.Post))
    {
        <div class="input-group">
            @Html.DropDownListFor(x => x.Bus ,Model.Buses, new { @class = "form-control" })
            <button type="submit" class="btn btn-success input-group-addon">Удалить</button>
        </div>
        @Html.HttpMethodOverride(HttpVerbs.Delete)
    }
</blockquote>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/DeleteBusRoute.cshtml
@model Application.Models.Admin.DeleteBusRouteViewModel

@{
    ViewBag.Title = "Удалить маршрут";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Удалить маршруты</h3>
    </div>
    @using (Html.BeginForm("DeleteBusRoute", "Admin", FormMethod.Post))
    {
        <div class="input-group">
            <span class="input-group-addon">Выберите автобус</span>
            @Html.DropDownListFor(x => x.Bus, Model.Buses,"", new { @class = "form-control" })
        </div>
        <hr />
        <button type="submit" class="btn btn-primary">Удалить</button>
        @Html.HttpMethodOverride(HttpVerbs.Delete)
    }
</blockquote>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/DeleteStop.cshtml
@model Application.Models.Admin.DeleteStopViewModel
@{
    ViewBag.Title = "Удалить остановку";
}

<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@Html.ValidationSummary()</p>

<blockquote>
    <div class="row">
        <h3 id="News" class="Title text-left col-lg-9">Удалить остановку</h3>
    </div>
    @using (Html.BeginForm("DeleteStop", "Admin", FormMethod.Post))
    {
        <div class="input-group">
            @Html.DropDownListFor(x => x.Stop, Model.Stops, new { @class = "form-control" })
            <button type="submit" class="btn btn-success input-group-addon">Удалить</button>
        </div>
        @Html.HttpMethodOverride(HttpVerbs.Delete)
    }
</blockquote>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Application/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@section styles
{
    @Styles.Render("~/Content/AdminIndex.css")
}
<p class="bg-success">@TempData["Success"]</p>
<p class="bg-danger">@TempData["Erors"]</p>
<div class="linkContainer">
    <a href="@Url.Action("AddFromFile")"><blockquote> <h4 class="text-muted">Создать расписание из файла</h4> </blockquote></a>
    <a href="@Url.Action("AddBus")"><blockquote> <h4 class="text-muted">Добавить автобус</h4> </blockquote></a>
    <a href="@Url.Action("DeleteBus")"><blockquote> <h4 class="text-muted">Удалить автобус</h4> </blockquote></a>
    <a href="@Url.Action("AddStop")"><blockquote> <h4 class="text-muted">Добавить остановку</h4> </blockquote></a>
    <a href="@Url.Action("DeleteStop")"><blockquote> <h4 class="text-muted">Удалить остановку</h4> </blockquote></a>
    <a href="@Url.Action("AddBusRoute")"><blockquote> <h4 class="text-muted">Добавить маршрут</h4> </blockquote></a>
    <a href="@Url.Action("DeleteBusRoute")"><blockquote> <h4 class="text-muted">Удалить маршруты</h4> </blockquote></a>
    <a href="@Url.Action("AddShedule")"><blockquote> <h4 class="text-muted">Добавить расписание</h4> </blockquote></a>
    <a href="@Url.Action("DeleteShedule")"><blockquote> <h4 class="text-muted">Удалить расписание</h4> </blockquote></a>
    @using (Html.BeginForm("DeleteAll","Admin"))
    {
        @Html.AntiForgeryToken()
        <button type="submit" class="link"><blockquote> <h4 class="text-muted">Удалить все записи</h4> </blockquote></button>
        @Html.HttpMethodOverride(HttpVerbs.Delete)
    }
    <a href="@Url.Action("Users","AdminManage")"><blockquote> <h4 class="text-muted">Управление пользователями</h4> </blockquote></a>
    <a href="@Url.Action("List","Cities")"><blockquote> <h4 class="text-muted">Города</h4> </blockquote></a>
    <a href="@Url.Action("List","News")"><blockquote> <h4 class="text-muted">Новости</h4> </blockquote></a>
</div>